# build stage
FROM golang:1.18-nanoserver-1809 AS builder

WORKDIR /workspace
# Copy the Go Module code
COPY go.mod ./go.mod
COPY go.sum ./go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download
COPY cmd/ ./cmd
COPY e2e/ ./e2e
COPY pkg/ ./pkg

# Build
ENV CGO_ENABLED=0 GOOS=windows GOARCH=amd64 
RUN go build -a -o thundernetes-nodeagent.exe ./cmd/nodeagent

FROM mcr.microsoft.com/windows/nanoserver:1809
WORKDIR /app
COPY --from=builder /workspace/thundernetes-nodeagent.exe /app/
ENTRYPOINT thundernetes-nodeagent.exe