# permissions for GameServer Pods 
# - sidecar needs to watch and patch GameServer and GameServerDetail CRs
# - initcontainer needs to query Node for the Public IP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gameserver-editor-role
rules:
- apiGroups:
  - mps.playfab.com
  resources:
  - gameservers
  verbs:
  - list
  - watch
- apiGroups:
  - mps.playfab.com
  resources:
  - gameservers/status
  verbs:
  - patch
- apiGroups:
  - mps.playfab.com
  resources:
  - gameserverdetails
  verbs:
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
