apiVersion: mps.playfab.com/v1alpha1
kind: GameServerBuild
metadata:
  name: gameserverbuild-sample-openarena
spec:
  titleID: "1E04" # required
  buildID: "85ffe8da-c82f-4035-86c5-9d2b5f42d6f7" # must be a GUID
  standingBy: 2 # required
  max: 4 # required
  portsToExpose:
    - 27960
  template:
    spec:
      containers:
        - image: ghcr.io/playfab/thundernetes-openarena:0.3.1
          name: thundernetes-sample-openarena
          ports:
          - containerPort: 27960 # your game server port
            protocol: UDP # your game server port protocol
            name: gameport # required field
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 100m
              memory: 500Mi