apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: qosserver
  name: qosserver-metrics-monitor
  namespace: system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: ${METRICS_SERVER_PORT}
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      name: qosserver