apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeagent-editor-role
rules:
- apiGroups:
  - mps.playfab.com
  resources:
  - gameservers
  verbs:
  - list
  - watch
- apiGroups:
  - mps.playfab.com
  resources:
  - gameservers/status
  verbs:
  - patch
- apiGroups:
  - mps.playfab.com
  resources:
  - gameserverdetails
  verbs:
  - get
  - patch