apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-load-simulator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      role: server-load-simulator
  template:
    metadata:
      labels:
        role: server-load-simulator
    spec:
      containers:
      - args:
        - "-maxValue=100"
        - "-jitter=0.15"
        image: ghcr.io/playfab/thundernetes-server-load-simulator:0.5
        imagePullPolicy: IfNotPresent        
        name: simulator
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: server-load-simulator
  namespace: default
  labels:
    role: server-load-simulator
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    role: server-load-simulator
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    role: server-load-simulator
  name: server-load-simulator
  namespace: default
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      role: server-load-simulator