# When this YAML file is used with kustomize, it adds the nodeSelector field to the controller deployment
# It's used in e2e tests, so that the gameserverapi is scheduled on a specific Node, so that we can do the 
# listening service port forwarding (5001) correctly
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thundernetes-gameserverapi
  namespace: thundernetes-system
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kind-worker