source 'https://rubygems.org'
gem 'nokogiri'
gem 'rack', '~> 2.1.4'
gem 'rspec'

gem "jekyll", "~> 4.2"

gem "jekyll-seo-tag", "~> 2.8"

gem "jekyll-sitemap", "~> 1.4"

gem "jemoji", "~> 0.12.0"

gem "jekyll-theme-primer", "~> 0.6.0"

gem "jekyll-github-metadata", "~> 2.15"

gem "jekyll-paginate", "~> 1.1"

gem "jekyll-relative-links", "~> 0.6.1"

gem "jekyll-remote-theme", "~> 0.4.3"

gem "just-the-docs", "~> 0.3.3"

gem "html-proofer", "~> 4.3.0"

gem "webrick", "~> 1.7"
