# this YAML file, when used with kustomize, it adds the nodeSelector field to the controller deployment
# it's used in e2e tests, so that the controller is scheduled on a different Node than the GameServer Pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kind-worker