# permissions for end users to view gameserverbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gameserverbuild-viewer-role
rules:
- apiGroups:
  - mps.playfab.com
  resources:
  - gameserverbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mps.playfab.com
  resources:
  - gameserverbuilds/status
  verbs:
  - get
