# permissions for end users to edit gameserverdetails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gameserverdetail-editor-role
rules:
- apiGroups:
  - mps.playfab.com
  resources:
  - gameserverdetails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mps.playfab.com
  resources:
  - gameserverdetails/status
  verbs:
  - get
