# permissions for end users to edit gameserverbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gameserverbuild-editor-role
rules:
- apiGroups:
  - mps.playfab.com
  resources:
  - gameserverbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mps.playfab.com
  resources:
  - gameserverbuilds/status
  verbs:
  - get
