# permissions for end users to view gameservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gameserver-viewer-role
rules:
- apiGroups:
  - mps.playfab.com
  resources:
  - gameservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mps.playfab.com
  resources:
  - gameservers/status
  verbs:
  - get
