name: Unit tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.18.x
      - name: check if Go utils need to be executed
        run: |
          go fmt ./...
          go vet ./...
          go mod tidy
          if ! [ -z "$(git status --porcelain)" ]; then
            echo "go utils need to be executed"
            exit 1
          fi
      # - name: check if install files are modified
      #   run: |
      #     make -C pkg/operator kustomize
      #     make create-install-files
      #     if ! [ -z "$(git status --porcelain)" ]; then
      #       echo "install files are modified"
      #       exit 1
      #     fi
      - name: GameServer API service unit tests
        run: cd cmd/gameserverapi && GIN_MODE=release go test -race
      - name: initcontainer unit tests
        run: cd cmd/initcontainer && go test -race
      - name: nodeagent unit tests
        run: cd cmd/nodeagent && go test -race
      - name: latency server server unit tests
        run: cd cmd/latencyserver && go test -race
      - name: operator unit tests
        run: make -C pkg/operator test